import { define, type ParameterDefinition, GA4_DOCS } from "./types";

const docs = GA4_DOCS;

/** GA4 standard & recommended event parameters (both `ep.*`/`epn.*` names and bare names). */
export const GA4_DEFINITIONS: ParameterDefinition[] = [
  define("value", "Value", "Numeric value associated with the event. For ecommerce events this is commonly the monetary value of the transaction.", "standard", { type: "number", documentationUrl: docs }),
  define("currency", "Currency", "Currency of the value, as a 3-letter ISO 4217 code (e.g. USD, EUR).", "standard", { type: "currency", documentationUrl: docs }),
  define("transaction_id", "Transaction ID", "A unique identifier for the transaction. Used by Google to identify duplicate events.", "standard", { type: "id", documentationUrl: docs }),
  define("items", "Items", "The items involved in the event, as a list of item objects.", "ecommerce", { type: "json", documentationUrl: docs }),
  define("coupon", "Coupon", "The coupon code used during a transaction.", "standard", { documentationUrl: docs }),
  define("shipping", "Shipping", "Shipping cost associated with a transaction.", "standard", { type: "number", documentationUrl: docs }),
  define("tax", "Tax", "Tax cost associated with a transaction.", "standard", { type: "number", documentationUrl: docs }),
  define("affiliation", "Affiliation", "A store or affiliation from which the transaction occurred.", "standard", { documentationUrl: docs }),
  define("content_type", "Content Type", "The type of content, e.g. 'product'.", "standard", { documentationUrl: docs }),
  define("content_id", "Content ID", "The ID of the content that was interacted with.", "standard", { type: "id", documentationUrl: docs }),
  define("content_ids", "Content IDs", "A list of content IDs involved in the event.", "standard", { type: "json", documentationUrl: docs }),
  define("content_name", "Content Name", "The name of the content that was interacted with.", "standard", { documentationUrl: docs }),
  define("content_category", "Content Category", "The category of the content that was interacted with.", "standard", { documentationUrl: docs }),
  define("content_group", "Content Group", "The content group of the content.", "standard", { documentationUrl: docs }),
  define("search_term", "Search Term", "The term used in a search.", "standard", { documentationUrl: docs }),
  define("item_id", "Item ID", "The ID of the item involved in the event.", "ecommerce", { type: "id", documentationUrl: docs }),
  define("item_name", "Item Name", "The name of the item involved in the event.", "ecommerce", { documentationUrl: docs }),
  define("item_brand", "Item Brand", "The brand of the item.", "ecommerce", { documentationUrl: docs }),
  define("item_category", "Item Category", "The category of the item.", "ecommerce", { documentationUrl: docs }),
  define("item_category2", "Item Category 2", "The second-level category of the item.", "ecommerce", { documentationUrl: docs }),
  define("item_category3", "Item Category 3", "The third-level category of the item.", "ecommerce", { documentationUrl: docs }),
  define("item_category4", "Item Category 4", "The fourth-level category of the item.", "ecommerce", { documentationUrl: docs }),
  define("item_category5", "Item Category 5", "The fifth-level category of the item.", "ecommerce", { documentationUrl: docs }),
  define("item_variant", "Item Variant", "The variant of the item, e.g. color or size.", "ecommerce", { documentationUrl: docs }),
  define("item_list_name", "Item List Name", "The name of the list in which the item was presented.", "ecommerce", { documentationUrl: docs }),
  define("item_list_id", "Item List ID", "The ID of the list in which the item was presented.", "ecommerce", { type: "id", documentationUrl: docs }),
  define("item_price", "Item Price", "The price of the item.", "ecommerce", { type: "number", documentationUrl: docs }),
  define("item_quantity", "Item Quantity", "The quantity of the item.", "ecommerce", { type: "number", documentationUrl: docs }),
  define("item_available", "Item Available", "Whether the item is available.", "ecommerce", { type: "boolean", documentationUrl: docs }),
  define("quantity", "Quantity", "The quantity of items involved in the event.", "ecommerce", { type: "number", documentationUrl: docs }),
  define("price", "Price", "The price of the item involved in the event.", "ecommerce", { type: "number", documentationUrl: docs }),
  define("promotion_id", "Promotion ID", "The ID of the promotion associated with the event.", "standard", { type: "id", documentationUrl: docs }),
  define("promotion_name", "Promotion Name", "The name of the promotion associated with the event.", "standard", { documentationUrl: docs }),
  define("creative_name", "Creative Name", "The name of the creative associated with the event.", "standard", { documentationUrl: docs }),
  define("creative_slot", "Creative Slot", "The name of the creative slot associated with the event.", "standard", { documentationUrl: docs }),
  define("location_id", "Location ID", "The ID of the location associated with the event.", "standard", { type: "id", documentationUrl: docs }),
  define("payment_type", "Payment Type", "The payment method used for the transaction.", "standard", { documentationUrl: docs }),
  define("discount", "Discount", "The monetary discount associated with the event.", "standard", { type: "number", documentationUrl: docs }),
  define("page_location", "Page Location", "The full URL of the page on which the event occurred.", "context", { type: "url", documentationUrl: docs }),
  define("page_title", "Page Title", "The title of the page on which the event occurred.", "context", { documentationUrl: docs }),
  define("page_referrer", "Page Referrer", "The URL of the page that referred traffic to the current page.", "context", { type: "url", documentationUrl: docs }),
  define("page_path", "Page Path", "The path portion of the page URL.", "context", { type: "url", documentationUrl: docs }),
  define("language", "Language", "The user's language setting, e.g. 'en-us'.", "context", { documentationUrl: docs }),
  define("screen_resolution", "Screen Resolution", "The user's screen resolution, e.g. '1920x1080'.", "context", { documentationUrl: docs }),
  define("user_id", "User ID", "An identifier associated with the logged-in user.", "standard", { type: "id", documentationUrl: docs }),
  define("session_id", "Session ID", "An identifier for the current session.", "standard", { type: "id", documentationUrl: docs }),
  define("engagement_time_msec", "Engagement Time", "The amount of time the user was engaged, in milliseconds.", "standard", { type: "number", documentationUrl: docs }),
  define("debug_mode", "Debug Mode", "Whether the event is being sent in debug mode.", "standard", { type: "boolean", documentationUrl: docs }),
  define("method", "Method", "The method used to complete an action, e.g. 'login'.", "standard", { documentationUrl: docs }),
  define("campaign", "Campaign", "The campaign name associated with the event.", "context", { documentationUrl: docs }),
  define("source", "Source", "The traffic source associated with the event.", "context", { documentationUrl: docs }),
  define("medium", "Medium", "The traffic medium associated with the event.", "context", { documentationUrl: docs }),
  define("term", "Term", "The term associated with the traffic source.", "context", { documentationUrl: docs }),
  define("gclid", "Google Click ID", "The Google Ads click identifier passed to the page.", "context", { type: "id", documentationUrl: "https://support.google.com/google-ads/answer/9744275" }),
  define("dclid", "Display Click ID", "The Google Marketing Platform click identifier.", "context", { type: "id" }),
  define("gbraid", "Google Ads ID (iOS)", "The Google Ads identifier for iOS app conversions.", "context", { type: "id", documentationUrl: "https://support.google.com/google-ads/answer/9744275" }),
  define("wbraid", "Google Ads ID (web)", "The Google Ads identifier for web conversions.", "context", { type: "id", documentationUrl: "https://support.google.com/google-ads/answer/9744275" }),
  define("gclsrc", "Google Click Source", "Indicates the click source, e.g. 'aw.ds' for Google Ads.", "context", { documentationUrl: "https://support.google.com/google-ads/answer/9744275" }),
  define("user_agent", "User Agent", "The user agent string of the browser.", "context", { documentationUrl: docs }),
  define("event_category", "Event Category", "Legacy Universal Analytics event category.", "standard", { documentationUrl: docs }),
  define("event_label", "Event Label", "Legacy Universal Analytics event label.", "standard", { documentationUrl: docs }),
  define("event_action", "Event Action", "Legacy Universal Analytics event action.", "standard", { documentationUrl: docs }),
  define("link_id", "Link ID", "The ID of the link that was clicked.", "standard", { type: "id", documentationUrl: docs }),
  define("link_classes", "Link Classes", "The CSS classes of the link that was clicked.", "standard", { documentationUrl: docs }),
  define("link_url", "Link URL", "The URL of the link that was clicked.", "standard", { type: "url", documentationUrl: docs }),
  define("link_domain", "Link Domain", "The domain of the link that was clicked.", "standard", { documentationUrl: docs }),
  define("form_id", "Form ID", "The ID of the form that was submitted.", "standard", { type: "id", documentationUrl: docs }),
  define("form_name", "Form Name", "The name of the form that was submitted.", "standard", { documentationUrl: docs }),
  define("form_destination", "Form Destination", "The URL that the form submits to.", "standard", { type: "url", documentationUrl: docs }),
  define("scroll_percent", "Scroll Percent", "The percentage of the page that was scrolled.", "standard", { type: "number", documentationUrl: docs }),
  define("file_name", "File Name", "The name of the file that was downloaded.", "standard", { documentationUrl: docs }),
  define("file_extension", "File Extension", "The extension of the file that was downloaded.", "standard", { documentationUrl: docs }),
  define("outbound", "Outbound", "Whether the click was to an external domain.", "standard", { type: "boolean", documentationUrl: docs }),
  define("video_title", "Video Title", "The title of the video that was engaged with.", "standard", { documentationUrl: docs }),
  define("video_url", "Video URL", "The URL of the video that was engaged with.", "standard", { type: "url", documentationUrl: docs }),
  define("video_duration", "Video Duration", "The duration of the video in seconds.", "standard", { type: "number", documentationUrl: docs }),
  define("video_progress", "Video Progress", "The progress of video playback.", "standard", { type: "number", documentationUrl: docs }),
  define("video_percent", "Video Percent", "The percentage of the video that was watched.", "standard", { type: "number", documentationUrl: docs }),
  define("video_provider", "Video Provider", "The provider of the video, e.g. 'youtube'.", "standard", { documentationUrl: docs }),
  define("error", "Error", "An error object or message captured by an event.", "standard", { documentationUrl: docs }),
  define("error_message", "Error Message", "A message describing an error.", "standard", { documentationUrl: docs }),
  define("error_type", "Error Type", "The type of error that occurred.", "standard", { documentationUrl: docs }),
  define("postal_code", "Postal Code", "The postal code associated with the event.", "standard", { documentationUrl: docs }),
  define("position", "Position", "The position of the item in a list.", "ecommerce", { type: "number", documentationUrl: docs }),
];

/** GA4 protocol/transport context parameters found in the collect query string. */
export const GA4_CONTEXT_DEFINITIONS: ParameterDefinition[] = [
  define("en", "Event Name", "The name of the event being sent to GA4.", "context", { documentationUrl: docs }),
  define("tid", "Measurement ID", "The GA4 measurement ID, e.g. G-XXXXXXXXXX. Identifies the data stream.", "context", { type: "id", documentationUrl: "https://support.google.com/analytics/answer/12270356" }),
  define("cid", "Client ID", "A persistent identifier for the user's browser, stored in the _ga cookie.", "context", { type: "id", documentationUrl: "https://developers.google.com/analytics/devguides/collection/protocol/ga4/user-id" }),
  define("sid", "Session ID", "An identifier for the current session.", "context", { type: "id", documentationUrl: docs }),
  define("sct", "Session Count", "The number of sessions for the current client.", "context", { type: "number" }),
  define("seg", "Session Number", "The number of the current session for the user.", "context", { type: "number", documentationUrl: docs }),
  define("dl", "Document Location", "The full URL of the page where the event was fired.", "context", { type: "url", documentationUrl: docs }),
  define("dr", "Document Referrer", "The URL of the referring page.", "context", { type: "url", documentationUrl: docs }),
  define("dt", "Document Title", "The title of the page where the event was fired.", "context", { documentationUrl: docs }),
  define("sr", "Screen Resolution", "The user's screen resolution.", "context", { documentationUrl: docs }),
  define("vp", "Viewport Size", "The visible viewport dimensions.", "context", { documentationUrl: docs }),
  define("sd", "Screen Depth", "The color depth of the screen.", "context", { documentationUrl: docs }),
  define("ul", "User Language", "The language of the browser, e.g. 'en-us'.", "context", { documentationUrl: docs }),
  define("v", "Protocol Version", "The GA4 protocol version (2 for GA4).", "context", { documentationUrl: docs }),
  define("gtm", "GTM Version", "The Google Tag Manager version that loaded gtag.js, if any.", "context", { documentationUrl: docs }),
  define("_z", "Cache Buster", "A cache-busting value appended to collect requests.", "context", { documentationUrl: docs }),
  define("_p", "Event Counter", "A per-session counter of events sent.", "context", { type: "number" }),
  define("_s", "Session Counter", "A counter of session starts in the current session.", "context", { type: "number" }),
  define("_ss", "Session Start", "Whether this event marks the start of a session.", "context", { type: "boolean" }),
  define("_dbg", "Debug Mode", "Whether the event is sent in debug mode (DebugView).", "context", { type: "boolean", documentationUrl: "https://support.google.com/analytics/answer/7201382" }),
  define("tfd", "Total Fetch Delay", "The total delay between a user interaction and the fetch, in ms.", "context", { type: "number" }),
  define("_fv", "First Visit", "Whether this is the first visit of the user.", "context", { type: "boolean" }),
  define("_nsi", "New Session Indicator", "Whether this session is a new session.", "context", { type: "boolean" }),
  define("_et", "Event Time", "Milliseconds since the start of the session when the event fired.", "context", { type: "number" }),
  define("_pn", "Page Number", "The page number within the session.", "context", { type: "number" }),
  define("_pcc", "Predefined Client Counters", "Counters that gtag.js maintains on the client.", "context", { type: "number" }),
  define("_pcp", "Predefined Client Params", "Predefined parameters maintained by gtag.js.", "context", { documentationUrl: docs }),
  define("gcd", "Consent State", "The Google consent mode state for ad_user_data and ad_personalization.", "context", { documentationUrl: "https://developers.google.com/tag-platform/security/concepts/consent-mode" }),
  define("ucm", "User Consent Mode", "Raw consent mode signal data.", "context", { documentationUrl: "https://developers.google.com/tag-platform/security/concepts/consent-mode" }),
];

export const GA4_DEFINITION_MAP = new Map(
  [...GA4_DEFINITIONS, ...GA4_CONTEXT_DEFINITIONS].map((d) => [d.name, d])
);